
version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/local_famous
      - JWT_SECRET=dev_secret_change_me
      - CORS_ORIGIN=http://localhost:5173
    ports: ["4000:4000"]
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:4000
    ports: ["5173:5173"]
    depends_on:
      - backend

volumes:
  mongo_data:
