version: "3.8"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev               # nodemon hot-reload in dev
    volumes:
      - ./backend:/app                 # mount code
      - /app/node_modules              # keep container deps isolated
    env_file:
      - ./backend/.env                 # put PORT, MONGO_URI, JWT_SECRET, CORS_ORIGIN here
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0   # Vite dev server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://localhost:4000  # frontend calls backend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
